### ISSUE TITLE
Some skills are listed more than once when adding skills in the Account Settings in the profile

### ISSUE THREAD

**Issue by naveejka** [topcoder-platform/Training-Challenges#107]
**Bug Title:** Some skills are listed more than once when adding skills in the Account Settings on the profile
**Steps to Reproduce:**
1. Click on the dropdown next to your handle on the top right hand corner.
2. Click on Settings.  
3. While still on the settings/Profile page, click on skills from the list on the left side.
4. From "Add a New skill" dropdown scroll to see the duplicates.

**Actual Result:**
Following duplicate skills were found:
Appium
C
Dimensionality Reduction
Genetic Algorithm/Genetic Algorithms
Machine Learning
R3 Corda
Regression
Salesforce/Salesforce.com
Selenium
Simulation

**Expected Result:** 
Skills shouldn't have any duplicates.

**Screenshots or screencast URL:**
![screencapture-topcoder-settings-profile-2020-04-28-12_48_17](https://user-images.githubusercontent.com/31006526/80458538-9183a680-894e-11ea-945a-8e903bfbaee0.png)

**Device/OS/Browser Information:**
Chrome on Windows 10

**Comment by nithyaasworld** [comment]
Good Job in finding this bug @naveejka 

Few Quick Tips:
1. Make sure the bug is visible in your screenshot. If the bug is about some action that cannot be captured in a screenshot, its best to provide a video.
2. When providing a screenshot, its a good practice to highlight the bug in the screenshot for easy-understanding. Below is a sample screenshot with bug- highlighted.

You should be able to participate in all sorts of Bug Hunt in Topcoder. Keep looking out for new Bug Hunt Projects in Topcoder and start participating. Ask in the challenge-forum if you run into any issues.
Happy Topcodering!!

Sample Screenshot:
![image](https://user-images.githubusercontent.com/5114190/80462602-93e8ff00-8954-11ea-9b7e-0501695346c4.png)
