### ISSUE TITLE
[UI Bug] Inconsistent span space in user's drop-down menu

### ISSUE THREAD

**Issue by JoeTinnySpace** [topcoder-platform/Training-Challenges#110]
**Steps to Reproduce**: After logged in, visiting https://www.topcoder.com or any other pages under topcoder domain ( https://www.topcoder.com/challenges?  , ) that features this drop-down menu.

**Actual Result**: The Drop-down flex menu shows inconsistent menu-item positions. 

**Expected Result**: The drop-down items should be listed continuously, consistently
**Screenshot**:
![Topcoder](https://user-images.githubusercontent.com/23105245/80473065-3dcf8800-8963-11ea-83c9-0c1eb9846b38.png)

**Device/OS/Browser Info**: Desktop PC/ Windows 10/ Firefox

**Comment by nithyaasworld** [comment]
@JoeTinnySpace This bug is similar to https://github.com/topcoder-platform/Training-Challenges/issues/94

Can you try once again please?

Hint for hunting more bugs: Check the website as if you are the end user. Try Editing your profile, adding skills to your profile, deleting skills, check the challenge listing page and different filters present in there, check your dashboard, check using mobile browsers, check using a tablet or iPad.
