### ISSUE TITLE
[Console-Error] Type error in console

### ISSUE THREAD

**Issue by papshoika** [topcoder-platform/Training-Challenges#120]
**Steps to Reproduce:**
1. Open the page https://www.topcoder.com/splash/ 
2. Press F12 and look at console errors - TypeError: headerNavUi is undefinedmain.js:176:20 will be there

**Actual Result:**
Type error
**Expected Result:** 
No errors in console
**OS/Browser Information:**
Ubuntu 16.04, Firefox Browser 75.0 (64-bit), Google Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
@papshoika I am not seeing any TypeError in my Console. Can you provide a screenshot of it?

Also, this will not come under 'Functional bug' if it does not affect any real function of the website.

**Comment by papshoika** [comment]
@nithyaasworld thanks for the feedback! Here is the screenshot:
![image](https://user-images.githubusercontent.com/7930250/80804070-bc733200-8bbc-11ea-9f0c-57d230cc45f2.png)

How could I find out if the error effects any function or not? I want to know how to correctly choose the but type. Or it is not a bug if nothing is broken?
Thanks in advance!

**Comment by nithyaasworld** [comment]
Thanks for the Screenshot @papshoika 

For me, This error is seen only in Firefox and not reproducible on Chrome. If its reproducible for you on Chrome, Please provide screenshot for that as well. Otherwise, please remove "Chrome browser" details from the OS/Browser-Information section of the bug.

Though this doesn't seem to affect any function of the app directly, it is worth to look into it and get it fixed. But this is not considered a Functional bug until its proved to affect any function of the app. At this point, we may call this as just 'Console-Error'. 

**It's always nice to report whatever error you see.** But let's make sure not to duplicate, suppose if we see similar console errors in some more pages, let's not create separate bugs for all these console errors which doesn't really affect any function/UI. But create just one bug and report all such errors under it.

**Comment by papshoika** [comment]
Thank you for so detailed answer! I will change the 'Functional bug' to 'Console-Error'. 
 On Chrome I see type error, too

![image](https://user-images.githubusercontent.com/7930250/80809827-2db9e180-8bcb-11ea-8b45-4718da27870a.png)
