### ISSUE TITLE
"member since" date is wrong in member search form.

### ISSUE THREAD

**Issue by gayand123** [topcoder-platform/Training-Challenges#34]
"member since" date is wrong in member search form.
Functional bug

Steps to Reproduce:
go to challenges form. - https://www.topcoder.com/challenges?filter[tags][0]=QA 
select the search option.
enter member name.
search.

Actual Result:
Member since the date is wrong. 
Expected Result: 
it should be displayed correctly which member registered date.
Screenshots or screencast URL:

![memeberfromdate](https://user-images.githubusercontent.com/32235212/70253236-d133d100-17a8-11ea-874d-ef99924c919a.png)

Device/OS/Browser Information:
Google Chrome 
Version 78.0.3904.108

**Comment by nithyaasworld** [comment]
This is a Great Catch @gayand123 !! I am sure you will be rocking in the real bug hunts. Please don't miss them. 

Again just make sure to number the steps. Then instead of saying a generic step _'enter member name'_, try to be as specific as possible. Because some issues may not occur for all the data. So it's always better to be more specific than generic.
