### ISSUE TITLE
New Offering Should Not Be Shown After Clicking On See More

### ISSUE THREAD

**Issue by devsreekrishna** [topcoder-platform/Training-Challenges#43]
1. Go To www.topcoder.com

2. Click On See More Option

3. Then See Screencast & Observe
[See More.mp4.zip](https://github.com/topcoder-platform/Training-Challenges/files/3992795/See.More.mp4.zip)

4. Actual Result: Again Its Showing New Offering Icon

5. Expected Result: It Should Not Show New Offering Icon

6. Device: Laptop

7. OS Detail: OS Version macOS High Sierra 10.13.6 (17G6029)

8. Browser Information: Browser Version Google Chrome 79.0.3945.88 (Official Build) (64-bit)

**Comment by nithyaasworld** [comment]
Good job in finding this bug @devsreekrishna 

But the reported format is not as expected. Please number only the steps to reproduce section. Do not number other sections like Actual result, expected result, etc

step3 should be something like 'Check the top purple banner' instead of 'See Screencast'

Refer [sample bugs](https://github.com/topcoder-platform/Training-Challenges/issues?q=is%3Aissue+is%3Aopen+label%3A%22Sample+Bug%22) for format to follow
