### ISSUE TITLE
The Username or member search button not working      

### ISSUE THREAD

**Issue by Rokit12** [topcoder-platform/Training-Challenges#6]
[searchbar.zip](https://github.com/topcoder-platform/Training-Challenges/files/3898326/searchbar.zip)
![search](https://user-images.githubusercontent.com/37167721/69750264-673e7a80-115d-11ea-8c5a-77ce3e1e1c8a.png)

1. Go to : https://www.topcoder.com/community/learn
 For instance, we want to search a member by the name "iaminfinite" or any other topcoder member
ACTUAL RESULT: Instead of giving out the given person as the searched result.It gives out this error : https://www.topcoder.com/search/members/?q=iaminfinite
 EXPECTED RESULT: The search button should give the result of the searched member of the topcoder.

Device/OS/Browser Information: Linux,Ubuntu
OS: Kali
Browser information: Chromium browser Version 73.0.3683.75 (Developer Build) built on Debian [buster/side,](url) running on Debian kali-rolling (32-bit)

**Comment by nithyaasworld** [comment]
@Rokit12 Congratulations on your first bug! You know in Bug hunt Challenges, Functional Bugs hold more value than any other type of bugs. It's awesome that your first bug is a Functional Bug.

Feedback:
1. To classify the bugs, please use the labels instead of the Title
2. Do not number the Expected Result
3. Use the same format as in the sample bug. Important thing is, each bug hunt may require little different format of reporting. So pay extra attention to this part and follow the instructions very carefully.

Nice Job!

**Comment by Rokit12** [comment]
i was unable to label. i dont know why in the label there is no setting icon to label the BUG

**Comment by nithyaasworld** [comment]
Ok, could be a permission issue. I will check and let you know on that part. Please implement the feedback provided.

**Comment by Rokit12** [comment]
Thank you, i will implement
