### ISSUE TITLE
No Alternate text on images

### ISSUE THREAD

**Issue by emerzon1** [topcoder-platform/Training-Challenges#97]
Steps to Reproduce: 
1. Go to https://www.topcoder.com
2. Scroll to the section that says "OUR CUSTOMERS,
THEIR SUCCESS"
3. Inspect element on the Microsoft image
4. No alt text.
Actual Result: No alternate text
Expected Result: Clear alternate text
<img width="283" alt="Screen Shot 2020-04-19 at 9 11 07 AM" src="https://user-images.githubusercontent.com/59055006/79688663-b7f26500-821d-11ea-9dc1-868c2bc96ee0.png">
Device: MacBook Air Catalina 2020, MacOSx

**Comment by nithyaasworld** [comment]
@emerzon1 Can you please add more details to the "Steps to Reproduce" section? Make sure to number the steps. 
You can refer [this bug](https://github.com/topcoder-platform/Training-Challenges/issues/90) to understand how detailed the "Steps to Reproduce" should be. 
General rule is that, the reader should be able to understand where the bug is, just by reading the "Steps to reproduce" (without seeing the screenshot or the video)
